### ISSUE TITLE
[Feature] `defineFontFace` macro

### ISSUE THREAD

**Issue by Bernankez** [Bernankez/vite-plugin-font-carrier#1]
### Usage

foo.ts
```ts
/// <reference types="vite-plugin-font-carrier" />

import MyFont from "./MyFont.ttf";

defineFontFace({
  fontFamily: "MyFont",
  src: `url("${MyFont}") local("Apple Color Emoji"), local("Segoe UI Emoji")`,
  input: "ABCDEFG", // Provide preset for numbers, alphabet
  unicodeRange: "U+1F000-1F644, U+203C-3299", // Optional
  fontStretch: "normal", // Optional
  fontStyle: "normal", // Optional
  fontWeight: "normal", // Optional
})
```

#### Transformed

foo.ts
```ts
import "bar.css";
```

bar.css
```css
@font-face {
  font-family: MyFont;
  src: url("./MyFont.ttf") local("Apple Color Emoji"), local("Segoe UI Emoji");
  unicode-range: U+1F000-1F644, U+203C-3299;
  font-stretch: normal;
  font-style: normal;
  font-weight: normal;
}
```

- The same font file options across files should be merged.
- Should be compatible with the existing `FontCarrier( { fonts: [] } )` configuration method.
- The font files introduced in this way will undergo `load` and `transform`, so real-time preview can be achieved in the dev environment. (https://github.com/vitejs/vite/discussions/7515#discussioncomment-2524204) (Temp font files can be stored in directories like .vite-font)
