### ISSUE TITLE
[Test] Improve testing case

### ISSUE THREAD

**Issue by Bernankez** [Bernankez/vite-plugin-font-carrier#2]
#### Case 1
```css
// with relative path in css
@font-face {
  font-family: Biantaoti;
  src: url("./assets/biantaoti.woff");
}
```

#### Case 2
```css
// with path alias in css
@font-face {
  font-family: Biantaoti;
  src: url("@/assets/biantaoti.woff");
}
```

#### Case 3
```css
// under public in css
@font-face {
  font-family: Biantaoti;
  src: url("/biantaoti.woff");
}
```

#### Case 4
```ts
// with relative path in js
import Biantaoti from "./assets/biantaoti.woff";
```

#### Case 5
```ts
// with path alias in js
import Biantaoti from "@/assets/biantaoti.woff";
```

#### Case 6
```ts
// under public in js
import Biantaoti from "/biantaoti.woff";
```

#### Case 7
```ts
// worker.ts

import Biantaoti from "@/assets/biantaoti.woff";

async function loadFont() {
  const response = fetch(Biantaoti);
  const blob = await response.blob();
  const buffer = await blob.arrayBuffer();
  const font = new FontFace("Biantaoti", buffer);
  await font.load();
  globalThis.fonts.add(font);
}

loadFont();

// Should fetch font with correct url
```

### Expected Behavior

Should convert all kinds of fonts above.
